[env]
TERM = "xterm-256color"

[font]
size = 8.0

[window]
opacity = 0.95

## COLOR SCHEME
[colors.primary]
background = "#09090d"
foreground = "#e3c7fc"

[colors.cursor]
text = "#09090d"
cursor = "#f1c4e0"

[colors.vi_mode_cursor]
text = "#f1c4e0"
cursor = "#edeff0"

[colors.search.matches]
foreground = "#09090d"
background = "#f1c4e0"

[colors.search.focused_match]
foreground = "#09090d"
background = "#262440"

[colors.footer_bar]
foreground = "#09090d"
background = "#f1c4e0"

[colors.hints.start]
foreground = "#09090d"
background = "#8897F4"

[colors.hints.end]
foreground = "#09090d"
background = "#f1c4e0"

[colors.selection]
text = "#09090d"
background = "#f1c4e0"

[colors.normal]
black = "#140a1d"
red = "#B52A5B"
green = "#FF4971"
yellow = "#8897F4"
blue = "#bd93f9"
magenta = "#E9729D"
cyan = "#F18FB0"
white = "#f1c4e0"

[colors.bright]
black = "#a8899c"
red = "#B52A5B"
green = "#FF4971"
yellow = "#8897F4"
blue = "#bd93f9"
magenta = "#E9729D"
cyan = "#F18FB0"
white = "#f1c4e0"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

## OTHER COLORS
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"
